# Labels
TITLE_LABEL = 'Data Scrambler'
OUTPUT_FOLDER_BUTTON_LABEL = 'Select output folder...'
CSV_FILE_SELECTION_BUTTON_LABEL = 'Select input CSV file...'
COLUMNS_TO_PRESERVE_LABEL = 'Columns to preserve'
COLUMNS_TO_PRESERVE_DEFAULT_VALUE = 'List columns not to be scrambled (comma-separated)...'
DATA_SCRAMBLER_BUTTON_LABEL = 'Scramble data from CSV file...'
QUIT_BUTTON_LABEL = 'Quit...'

# Elements coordinates
TITLE_LABEL_COORDINATES = (0,0)
QUIT_BUTTON_COORDINATES = (5,0)
OUTPUT_FOLDER_BUTTON_COORDINATES = (3,0)
OUTPUT_FOLDER_LABEL_COORDINATES = (3,1)
COLUMNS_TO_PRESERVE_LABEL_COORDINATES = (1,0)
COLUMNS_TO_PRESERVE_ENTRY_COORDINATES = (1,1)
CSV_FILE_SELECTION_BUTTON_COORDINATES = (2,0)
CSV_FILE_SELECTION_LABEL_COORDINATES = (2,1)
DATA_SCRAMBLER_BUTTON_COORDINATES = (4,0)